export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_HOMES_SUCCESS = "GET_HOMES_SUCCESS";

export const GET_TENANT_SUCCESS = "GET_TENANT_SUCCESS";

export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const CHANGE_CITY = "CHANGE_CITY";

